version: '3'
services:
  api-server: 
    image: api-server
    build: .
    ports: 
    - '8000:8000'
    links: 
    - mongo 
    networks:
     - e-commerce
    depends_on: 
     - mongo
  mongo: 
    image: mongo:4.4-bionic
    ports: 
     - '27018:27017'
    networks: 
     - e-commerce
  react-app:
   image: react-app
   build: ./client/
   stdin_open: true
   networks:
    - e-commerce
   ports:
     - '3000:3000'
   volumes: 
    - /app/node-modules
    - ./client/:/app  
networks:
 e-commerce:
  driver: bridge
  
      